# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, path: "install-sw.sh"

  config.vm.synced_folder ".", "/vagrant_dir" 

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "Coarray Fortran VM"
    vb.customize ["modifyvm", :id, "--memory", "2048" ]
    vb.cpus = 4
  end

end
